import { ArrowLeft, Bell, Download, Moon, MoonStar, RotateCcw, Upload, Video } from 'lucide-react';
import type { AppSettings } from '../../persistence/db';

export function Settings({ settings, restoreStatus, onChange, onExport, onImport, onReset, onBack }: { settings: AppSettings; restoreStatus?: string; onChange: (settings: AppSettings) => void; onExport: () => void; onImport: (file: File) => void; onReset: () => void; onBack?: () => void }) {
  return <div className="page-pad page-content">{onBack ? <button className="back-button" onClick={onBack}><ArrowLeft size={18} /> Kembali</button> : null}<p className="eyebrow">PREFERENSI</p><h1>Pengaturan</h1>
    <section className="settings-card"><label><Moon /><span><strong>Tampilan</strong><small>Ikuti HP atau pilih tema</small></span><select value={settings.theme} onChange={(event) => onChange({ ...settings, theme: event.target.value as AppSettings['theme'] })}><option value="system">Otomatis</option><option value="light">Terang</option><option value="dark">Gelap</option></select></label><label><Video /><span><strong>Video panduan</strong><small>Video resmi membutuhkan internet</small></span><input type="checkbox" checked={settings.videoConsent} onChange={(event) => onChange({ ...settings, videoConsent: event.target.checked })} /></label></section>
    <section className="settings-card"><div className="setting-summary"><Bell /><span><strong>{settings.reminder.enabled ? 'Pengingat latihan aktif' : 'Pengingat latihan nonaktif'}</strong><small>{settings.reminder.trainingDays.length} hari · {settings.reminder.trainingTime}</small></span></div><div className="setting-summary"><MoonStar /><span><strong>{settings.tahajjud.enabled ? 'Rutinitas tahajjud aktif' : 'Rutinitas tahajjud nonaktif'}</strong><small>Tidur {settings.tahajjud.bedTime} · Bangun {settings.tahajjud.wakeTime}</small></span></div></section>
    <section className="settings-card"><label><span aria-hidden="true">1–4</span><span><strong>Minggu aktif</strong><small>Ulangi minggu jika tubuh belum nyaman</small></span><select aria-label="Minggu aktif" value={settings.programWeek} onChange={(event) => onChange({ ...settings, programWeek: Number(event.target.value) as AppSettings['programWeek'] })}>{[1,2,3,4].map((week) => <option key={week} value={week}>Minggu {week}</option>)}</select></label><button onClick={onExport}><Download /><span><strong>Ekspor progres</strong><small>Simpan cadangan JSON di HP</small></span></button><label className="file-button"><Upload /><span><strong>Impor progres</strong><small>Pulihkan dari cadangan JSON</small></span><input aria-label="Pilih cadangan progres" type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) onImport(file); }} /></label><button className="danger-button" onClick={onReset}><RotateCcw /><span><strong>Hapus progres</strong><small>Tindakan ini tidak dapat dibatalkan</small></span></button></section>
    {restoreStatus ? <p className="restore-status" role="status">{restoreStatus}</p> : null}
    <div className="privacy-block"><strong>Privasi sederhana</strong><p>JagaRaga tidak memakai akun, iklan, analitik, atau pelacak lokasi. Data latihan hanya ada di browser HP ini.</p></div><p className="version">JagaRaga v3 · Mode 1</p>
  </div>;
}
