import { ArrowLeft, Moon, Save } from 'lucide-react';
import { useState } from 'react';
import type { DayKey, TahajjudEntry } from '../../domain/types';
import type { AppSettings } from '../../persistence/db';

const days: { id: DayKey; label: string }[] = [{ id: 'monday', label: 'Sen' }, { id: 'tuesday', label: 'Sel' }, { id: 'wednesday', label: 'Rab' }, { id: 'thursday', label: 'Kam' }, { id: 'friday', label: 'Jum' }, { id: 'saturday', label: 'Sab' }, { id: 'sunday', label: 'Min' }];

export function Tahajjud({ settings, today, entries, onSettingsChange, onSaveEntry, onBack }: { settings: AppSettings; today: string; entries: TahajjudEntry[]; onSettingsChange: (settings: AppSettings) => void | Promise<void>; onSaveEntry: (entry: TahajjudEntry) => void | Promise<void>; onBack: () => void }) {
  const [routine, setRoutine] = useState(settings.tahajjud);
  const current = entries.find((entry) => entry.id === today);
  const [sleptOnTime, setSleptOnTime] = useState(current?.sleptOnTime ?? false);
  const [wokeOnTime, setWokeOnTime] = useState(current?.wokeOnTime ?? false);
  const [prayed, setPrayed] = useState(current?.prayed ?? false);
  const [readiness, setReadiness] = useState<number>(current?.readiness ?? 3);
  const [note, setNote] = useState(current?.note ?? '');
  const toggleDay = (day: DayKey) => setRoutine((value) => ({ ...value, weekdays: value.weekdays.includes(day) ? value.weekdays.filter((item) => item !== day) : [...value.weekdays, day] }));
  return <section className="page-pad page-content tahajjud-page"><button className="back-button" onClick={onBack}><ArrowLeft size={18} /> Kembali</button><div className="safety-icon"><Moon /></div><p className="eyebrow">RUTINITAS MALAM</p><h1>Tahajjud & Pemulihan</h1><p className="lead">Atur tidur dan bangun secara realistis agar ibadah tidak dibayar dengan kelelahan berlebihan.</p>
    <section className="routine-card"><label className="switch-row"><span><strong>Aktifkan rutinitas</strong><small>Tampilkan jadwal tidur dan bangun</small></span><input aria-label="Aktifkan rutinitas" type="checkbox" checked={routine.enabled} onChange={(event) => setRoutine({ ...routine, enabled: event.target.checked })} /></label><div className="time-pair"><label className="field"><span>Waktu tidur</span><input aria-label="Waktu tidur" type="time" value={routine.bedTime} onChange={(event) => setRoutine({ ...routine, bedTime: event.target.value })} /></label><label className="field"><span>Waktu bangun</span><input aria-label="Waktu bangun" type="time" value={routine.wakeTime} onChange={(event) => setRoutine({ ...routine, wakeTime: event.target.value })} /></label></div>
      <fieldset className="day-picker"><legend>Hari pengingat</legend>{days.map((day) => <label key={day.id}><input type="checkbox" checked={routine.weekdays.includes(day.id)} onChange={() => toggleDay(day.id)} /><span>{day.label}</span></label>)}</fieldset><label className="field"><span>Mobilitas ringan</span><select aria-label="Mobilitas ringan" value={routine.mobilityMinutes} onChange={(event) => setRoutine({ ...routine, mobilityMinutes: Number(event.target.value) as AppSettings['tahajjud']['mobilityMinutes'] })}><option value="0">Tanpa mobilitas</option><option value="3">3 menit</option><option value="5">5 menit</option><option value="10">10 menit</option></select></label><button className="secondary-button wide" onClick={() => void onSettingsChange({ ...settings, tahajjud: routine })}><Save size={18} /> Simpan pengaturan</button></section>
    <section className="routine-card"><p className="eyebrow">CATATAN HARI INI</p><h2>Refleksi singkat</h2><label className="accept-row"><span>Tidur sesuai rencana</span><input type="checkbox" checked={sleptOnTime} onChange={(event) => setSleptOnTime(event.target.checked)} /></label><label className="accept-row"><span>Bangun sesuai rencana</span><input type="checkbox" checked={wokeOnTime} onChange={(event) => setWokeOnTime(event.target.checked)} /></label><label className="accept-row"><span>Sempat tahajjud</span><input aria-label="Sempat tahajjud" type="checkbox" checked={prayed} onChange={(event) => setPrayed(event.target.checked)} /></label><label className="scale-field"><span><strong>Kesiapan fisik</strong><b>{readiness}</b></span><input type="range" min="1" max="5" value={readiness} onChange={(event) => setReadiness(Number(event.target.value))} /></label><label className="field"><span>Catatan tahajjud <small>{note.length}/280</small></span><textarea aria-label="Catatan tahajjud" maxLength={280} value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="primary wide" onClick={() => void onSaveEntry({ id: today, sleptOnTime, wokeOnTime, prayed, readiness: readiness as TahajjudEntry['readiness'], note, updatedAt: new Date().toISOString() })}>Simpan catatan tahajjud</button></section>
  </section>;
}
